Controllers/AnswersController.cs
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using MaturaToBzdura.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using wiKorki.Data.ViewModels;
using wiKorki.Models;

namespace wiKorki.Controllers
{
    public class AnswersController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public AnswersController(AppDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Admin"))
            {
                var answers = await _context.Answers.Include(a => a.ApplicationUser).Include(a => a.Exercise).ToListAsync();

                return View("AdminIndex", answers);
            }
            else if (User.IsInRole("User"))
            {
                var curUser = await _userManager.GetUserAsync(User);
                var curUserId = curUser.Id.ToString();

                if (curUser != null)
                {
                    var answers = await _context.Answers.Where(a => a.ApplicationUser.Id == curUserId).Include(a => a.Exercise).ToListAsync();
                
                    return View("UserIndex", answers);
                }
            }
            return NotFound();
        }

        public async Task<IActionResult> GetImage(int id)
        {
            var answer = await _context.Answers.FirstOrDefaultAsync(a => a.Id == id);
            if (answer != null && answer.Image != null)
            {
                return File(answer.Image, "image/jpeg");
            }
            return NotFound();
        }

        public async Task<IActionResult> Create(AddAnswerVM model, IFormFile imageFile)
        {
            ModelState.Clear();

            if (User.Identity.IsAuthenticated)
            {

                if (imageFile == null || imageFile.Length == 0)
                {
                    TempData["ErrorMessage"] = "Plik jest wymagany!";
                    return RedirectToAction("Details", "Exercises", new { id = model.ExerciseId });
                }
                else
                {
                    model.Image = await ConvertFileToByteArrayAsync(imageFile);
                }

                if (!ModelState.IsValid)
                {
                    TempData["ErrorMessage"] = "Plik jest wymagany!";
                    return RedirectToAction("Details", "Exercises", new { id = model.ExerciseId });
                }

                var answer = new Answer
                {
                    ExerciseId = model.ExerciseId,
                    ApplicationUser = await _userManager.GetUserAsync(User),
                    Image = model.Image
                };

                _context.Answers.Add(answer);
                await _context.SaveChangesAsync();
                TempData["SuccessMessage"] = "Twoje rozwiązanie zostało przesłane. Poczekaj na ocenę.";
                return RedirectToAction("Details", "Exercises", new { id = model.ExerciseId });

            }
            else
            {

                HttpContext.Session.SetString("ReturnUrl", Url.Action("Details", "Exercises", new { id = model.ExerciseId }));
                return RedirectToAction("Login", "Account");
            }
        }

        private async Task<byte[]> ConvertFileToByteArrayAsync(IFormFile file)
        {
            using (var memoryStream = new MemoryStream())
            {
                await file.CopyToAsync(memoryStream);
                return memoryStream.ToArray();
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddEvaluation(int answerId, string evaluation)
        {
            var answer = await _context.Answers.FindAsync(answerId);
            if (answer == null)
            {
                return NotFound();
            }
            answer.Evaluation = evaluation;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteEvaluation(int answerId)
        {
            var answer = await _context.Answers.FindAsync(answerId);

            if (answer == null)
            {
                return NotFound();
            }

            answer.Evaluation = null;
            _context.Update(answer);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAnswer(int answerId)
        {
            var answer = await _context.Answers.FindAsync(answerId);

            if (answer == null)
            {
                return NotFound();
            }

            _context.Answers.Remove(answer);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_AboutMe.cshtml
@{
    ViewData["Title"] = "O mnie";
}

<section id="AboutMe" class="bg-dark">
    <div class="container py-5">

        <div class="justify-content-center align-items-center ">
            <h2 class="text-center text-white">
                O mnie
            </h2>
            <div class="col-md ">
                <div class="card-body text-center text-light bg-dark mb-3">
                    <img src="/pics/aboutMe1.jpg" id="about-me-img" class="rounded-circle mb-3 lg-img" alt="">
                    <h3 class="card-title text-light m-b">Wiktoria Solska</h3>
                    <p class="card-text text-light">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, minima. Consequuntur veritatis aperiam est ipsum.</p>
                    <a href="https://www.linkedin.com/in/wiktoria-solska-97b289272/" target="_blank"><i class="bi bi-linkedin text-light"></i></a>
                    |
                    <a href="#"><i class="bi bi-instagram text-light"></i></a>
                    |
                    <a href="#"><i class="bi bi-facebook text-light"></i></a>
                </div>
            </div>
            <div>
                <ul class="list-group  lead">
                    <li class="list-group-item list-group-item-action list-group-item-dark">
                        <span class="fw-bold">Lokalizacja: </span> Wrocław
                    </li>
                    <li class="list-group-item list-group-item-action list-group-item-dark">
                        <span class="fw-bold">Kontakt mailowy:  </span>wiksolska@gmail.com
                    </li>
                </ul>
            </div>

        </div>
    </div>
</section>

<script>
    window.addEventListener('resize', function () {

        var screenWidth = window.innerWidth;

        if (screenWidth <= 500) {
            var imgToResize = document.getElementById('about-me-img');
            imgToResize.classList.remove("lg-img");
            imgToResize.classList.add("sm-img");
            
        } else {

            var imgToResize = document.getElementById('about-me-img');
            imgToResize.classList.remove("sm-img");
            imgToResize.classList.add("lg-img");
        }
    });

    window.addEventListener('load', function () {

        window.dispatchEvent(new Event('resize'));
    });
</script>

Views/Shared/_AddAnswers.cshtml
@model AddAnswerVM

@if (!User.IsInRole("Admin"))
{
    <div class="px-5 py-2">
        <h3 class="my-3">Twoja odpowiedź <i class="bi bi-pencil"></i></h3>
        @if (TempData["SuccessMessage"] != null)
        {
            <div class="col-md-6 alert alert-success">@TempData["SuccessMessage"]</div>
        }

        @using (Html.BeginForm("Create", "Answers", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(m => m.ExerciseId)
            <div class="form-group ">
                <input class="form-control-file" type="file" name="imageFile" />
                @if (TempData["ErrorMessage"] != null)
                {
                    <span class="text-danger">@TempData["ErrorMessage"]</span>
                }

            </div>
            <div class="form-group">
                <button class="btn btn-outline-success float-left" type="submit">dodaj</button>
            </div>
        }
    </div>
}

Views/Shared/_Breadcrumb.cshtml
@model IList<MvcBreadcrumbNode>


@if (Model != null && Model.Count > 0)
{
    <div class="container rounded bg-dark text-light">
        <ol class="breadcrumb mb-0 mt-3 bg-dark">
            @foreach (var node in Model)
            {
                <li class="breadcrumb-item">
                    <a id="ala" asp-controller="@node.Controller" asp-action="@node.Action" asp-route-id="@((node as MyMvcBreadcrumbNode)?.Id)">@node.Title</a>
                </li>
            }
        </ol>

    </div>
}

Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;

@if (User.Identity.IsAuthenticated)
{
    <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopop="true" aria-expanded="false">
            <h5 class="text-brand">Witaj @User.Identity.Name </h5>
        </a>
        <div class="dropdown-menu text-center bg-dark" aria-labelledby="navbarDropdown">

            @if (User.IsInRole("Admin"))
            {
                <a class="dropdown-item text-light bg-dark " asp-controller="Account" asp-action="Users">Użytkownicy <i class="bi bi-list"></i></a>
                <div class="dropdown-divider text-light bg-dark"></div>

            }
            <a class="dropdown-item text-light bg-dark " asp-controller="Answers" asp-action="Index">Rozwiązania zadań <i class="bi bi-list"></i></a>
            <div class="dropdown-divider text-light bg-dark"></div>
            <a class="dropdown-item text-light bg-dark " asp-controller="Account" asp-action="MyAccount">
                Moje konto <i class="bi bi-person-circle"></i>
            </a>
            <div class="dropdown-divider text-light bg-dark"></div>
            <a class="dropdown-item text-light bg-dark " asp-controller="Account" asp-action="Logout">
                Wyloguj się <i class="bi bi-box-arrow-in-right"></i>
            </a>
            <div class="dropdown-divider text-light bg-dark"></div>
        </div>

    </li>

}
else
{
    <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopop="true" aria-expanded="false">
            <h5 class="text-brand">Logowanie</h5>
        </a>
        <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
            <a class="dropdown-item text-light bg-dark " asp-controller="Account" asp-action="Login">Zaloguj się <i class="bi bi-person-fill"></i></a>
            <div class="dropdown-divider text-light bg-dark"></div>
            <a class="dropdown-item text-light bg-dark" asp-controller="Account" asp-action="Register">Załóż konto <i class="bi bi-person-add"></i></a>
        </div>
    </li>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>wiKorki -  @ViewData["Title"] </title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/styles.css" />
    <style>
        .dropdown-toggle::after {
            display: none;
        }

        .dropdown:hover .dropdown-menu {
            display: block;
        }
    </style>
</head>
<body>
    <header>
        <nav id="navbar" class="navbar navbar-expand-lg bg-light navbar-light  py-2 fixed-top border-bottom-secondary mb-5">
            <div class="container">
                <a class="navbar-brand hover" asp-controller="Home" asp-action="Index"><h4>wi<span class="text-brand">Korki</span></h4></a>

                <button class="navbar-toggler"
                        type="button"
                        data-toggle="collapse"
                        data-target="#navmenu">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse  navbar-collapse justify-content-end" id="navmenu">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle"
                               id="navbarDropdown"
                               role="button"
                               data-toggle="dropdown"
                               aria-expanded="false"
                               asp-controller="HSClasses"
                               asp-action="Details"
                               asp-route-id="1">
                                <h5>Klasa 1</h5>
                            </a>
                            @await Component.InvokeAsync("DropdownList", new { id = 1 })
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle"
                               id="navbarDropdown"
                               role="button"
                               data-toggle="dropdown"
                               aria-haspopop="true"
                               aria-expanded="false"
                               asp-controller="HSClasses"
                               asp-action="Details"
                               asp-route-id="2">
                                <h5>Klasa 2</h5>
                            </a>
                            @await Component.InvokeAsync("DropdownList", new { id = 2 })
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle"
                               id="navbarDropdown"
                               role="button"
                               data-toggle="dropdown"
                               asp-controller="HSClasses"
                               asp-action="Details"
                               asp-route-id="3"><h5>Klasa 3</h5></a>
                            @await Component.InvokeAsync("DropdownList", new { id = 3 })
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link" id="aboutMeLink" asp-controller="Home" asp-action="RenderAboutMeView"><h5>O mnie</h5></a>
                        </li>
                        <partial name="_Identity.cshtml" />

                    </ul>
                </div>

            </div>
        </nav>
    </header>

    <div class="container-fluid justify-content-center mt-5">
        <main role="main" class="p-3">
            <nav aria-label="breadcrumb">
                <partial name="_Breadcrumb" for="@ViewData["BreadcrumbNodes"]" />
            </nav>
            @RenderBody()
        </main>
    </div>

    <footer class="footer bg-light  mt-auto fixed-bottom border-top-secondary">
        <div class="container text-center ">
            <p class=" m-2 lead">Copyright &copy <span id="currentYear"></span> wiKorki</p>
        </div>
    </footer>

    <script>
        function scrollTo() {
            var target = $('#AboutMe');
            $('html,body').animate({
                scrollTop: target.offset().top
            }, 1000);
        }

        var currentYear = new Date().getFullYear();
        document.getElementById('currentYear').innerText = currentYear;
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>