Controllers/CommentController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using MaturaToBzdura.Data;
using MaturaToBzdura.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using wiKorki.Data.ViewModels;

namespace wiKorki.Controllers
{
    public class CommentController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CommentController(AppDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var comment = _context.Comments.ToList();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AddCommentVM model)
        {
            if (model.Text == null || model.Text.Length < 1)
            {
                
                return RedirectToAction("Details", "Exercises", new { id = model.ExerciseId });
            }
            
            if (ModelState.IsValid)
            {
                if (User.Identity.IsAuthenticated)
                {
                    var user = await _userManager.GetUserAsync(User);
                    var comment = new Comment
                    {
                        ExerciseId = model.ExerciseId,
                        Text = model.Text,
                        CreatedAt = DateTime.Now,
                        UserId = user.Id
                    };               

                    _context.Comments.Add(comment);
                    var commentId = comment.Id;
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Details", "Exercises", new { id = model.ExerciseId });
                } else { 
                    HttpContext.Session.SetString("ReturnUrl", Url.Action("Details", "Exercises", new { id = model.ExerciseId }));
                    return RedirectToAction("Login", "Account");
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var comment = await _context.Comments.FindAsync(id);

            if (comment == null)
            {
                return NotFound();
            }

            _context.Comments.Remove(comment);
            await _context.SaveChangesAsync();

            return RedirectToAction("Details", "Exercises", new { id = comment.ExerciseId });
        }
    }
}

Controllers/ExercisesController.cs
using System.Collections.Generic;
using System.Linq;
using MaturaToBzdura.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SmartBreadcrumbs.Nodes;
using wiKorki.Data;

namespace MaturaToBzdura.Controllers
{
    public class ExercisesController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ExercisesController(AppDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            var exercise = _context.Exercises.Include(e => e.Chapter).FirstOrDefault(e => e.Id == id);
            var chapter = _context.Chapters.Include(c => c.HSClass).FirstOrDefault(c => c.Id == exercise.Chapter.Id);
            var hSClass = chapter.HSClass;

            var homeNode = new MvcBreadcrumbNode("Index", "Home", "Strona Główna");
            var hSClassNode = new MyMvcBreadcrumbNode("Details", "HSClasses", hSClass.Name, hSClass.Id) { Parent = homeNode };
            var chapterNode = new MyMvcBreadcrumbNode("Details", "Chapters", chapter.Name, chapter.Id) { Parent = hSClassNode };
            var exerciseNode = new MyMvcBreadcrumbNode("Details", "Exercises", exercise.Name, exercise.Id) { Parent = chapterNode };

            ViewData["BreadcrumbNodes"] = new List<MvcBreadcrumbNode> { homeNode, hSClassNode, chapterNode, exerciseNode };
           
            var result = _context.Exercises.First(n => n.Id == id);
            return View(result);
        }
    }
}

Data/ViewComponents/CommentsViewComponent.cs
using System.Linq;
using System.Threading.Tasks;
using MaturaToBzdura.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace wiKorki.Data.ViewComponents
{
    public class CommentsViewComponent : ViewComponent
    {
        private readonly AppDbContext _context;

        public CommentsViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync(int exerciseId)
        {
            var comments = await _context.Comments.Where(c => c.ExerciseId == exerciseId).Include(c => c.User).ToListAsync();
            return View(comments);
        }
    }
}

Views/Exercises/Details.cshtml
@model Exercise

@{
    ViewData["Title"] = "Rozwiąż Zadanie";
}

<section class="p-4 mb-2">
    <div class="container bg-secondary text-light">
        <h2 class="text-center py-4">@Model.Name</h2>
        <div class="p-5 text-center">
            <span class="lead">@Model.Content</span>
        </div>


        <partial name="_AddAnswers" model="@new AddAnswerVM { ExerciseId = Model.Id }" />

        @*display comments*@

        @await Component.InvokeAsync("Comments", new { exerciseId = Model.Id })

        <partial name="_AddComments" model="@new AddCommentVM { ExerciseId = Model.Id }" />

    </div>
</section>

Views/Exercises/_AddComments.cshtml
@model AddCommentVM


    <div class="container py-5">
        <div class="justify-content-center align-items-center">
            <div class="col-md-8">

                <h3>Dodaj komentarz <i class="bi bi-send-plus-fill"></i></h3>

                @using (Html.BeginForm("Create", "Comment", FormMethod.Post))
                {
                    @Html.HiddenFor(m => m.ExerciseId)

                    <div class="form-group dark-border-focus">
                        @Html.TextAreaFor(m => m.Text, new { rows = "4", cols = "50", @class = "form-control text-light border border-light bg-dark btn-outline-dark", placeholder = "Wpisz treść...." })
                        @Html.ValidationMessageFor(m => m.Text, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <input class="btn btn-outline-success float-left" type="submit" value="dodaj" />
                    </div>
                }
            </div>
        </div>
    </div>